services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: FastAPI_Backend
    ports:
      - '8000:8000'
    volumes:
      - ./Backend/src:/app/src
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
